/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/p1GoOwSqAyx
 */
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import Link from "next/link"

export function Component() {
  return (
    <header className="flex items-center justify-between  sm:hidden ">
      
      <Sheet>
        <SheetTrigger asChild>
          <Button size="icon" >
            <IconMenu className="h-8 w-8 text-zinc-50 dark:text-zinc-900" />
          </Button>
        </SheetTrigger>
        <SheetContent className="w-full  bg-zinc-900/90 dark:bg-zinc-50 border-neutral-800 shadow-xl transition-all duration-500 ease-in-out" side="top">
          <nav className="mt-4 space-y-4 text-zinc-300">
          <Link
              className="block  font-medium "
              href="/"
            >
              Home
            </Link>
            <Link
              className="block  font-medium "
              href="/about"
            >
              About
            </Link>
            <Link
              className="block  font-medium "
              href="/services"
            >
              Services
            </Link>
            <Link
              className="block  font-medium "
              href="/projects"
            >
              Projects
            </Link>
            <Link
              className="block  font-medium "
              href="/contact"
            >
              Contact
            </Link>
          </nav>
        </SheetContent>
      </Sheet>
    </header>
  )
}


function IconMenu(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function IconHome(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}
